version: 0.2

phases:
  build:
    commands:
      - mvn clean
      - mvn install
artifacts:
  files:
    - 'appspec.yml'
    - 'deploy/before_install'
    - 'deploy/restart_server'
    - 'target/sample-1.0.0.jar'
    